apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-distributed-ml
  labels:
    app: distributed-ml
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: distributed-ml
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: distributed-ml
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: distributed-ml-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        env:
        - name: LOG_LEVEL
          value: {{ .Values.environment.logLevel }}
        - name: MPI_NODES
          value: {{ .Values.environment.mpiNodes | quote }}
# TODO: Improve resource management
# TODO: Implement more scalable architecture
